name: Bump

on:
  push:
    branches:
      - 'main'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bump
        run: bash scripts/bump_version.sh ${{ github.event.head_commit.message }}

      - name: Commit
        env:
          CI_COMMIT_AUTHOR: bump_bot
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git add package.json
          git config --global user.name '${{ env.CI_COMMIT_AUTHOR }}'
          git config --global user.email 'username@users.noreply.github.com'
          git commit -m 'bump version to $VERSION [skip actions]'
          git push origin main
